// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Data;

#nullable disable

namespace MyWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyWebApi.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountNumber = "10010001",
                            AccountType = "Checking",
                            Balance = 1000.00m,
                            UserId = 1
                        },
                        new
                        {
                            AccountId = 2,
                            AccountNumber = "10010002",
                            AccountType = "Savings",
                            Balance = 2500.50m,
                            UserId = 2
                        },
                        new
                        {
                            AccountId = 3,
                            AccountNumber = "10010003",
                            AccountType = "Checking",
                            Balance = 300.75m,
                            UserId = 3
                        },
                        new
                        {
                            AccountId = 4,
                            AccountNumber = "10010004",
                            AccountType = "Savings",
                            Balance = 4200.00m,
                            UserId = 4
                        },
                        new
                        {
                            AccountId = 5,
                            AccountNumber = "10010005",
                            AccountType = "Checking",
                            Balance = 150.00m,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("MyWebApi.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountId = 1,
                            Amount = 200.00m,
                            CreatedAt = new DateTime(2025, 10, 8, 19, 14, 48, 933, DateTimeKind.Local).AddTicks(9891),
                            Description = "Initial deposit",
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountId = 2,
                            Amount = 150.50m,
                            CreatedAt = new DateTime(2025, 10, 8, 19, 14, 48, 934, DateTimeKind.Local).AddTicks(133),
                            Description = "Salary deposit",
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 3,
                            AccountId = 3,
                            Amount = -50.25m,
                            CreatedAt = new DateTime(2025, 10, 8, 19, 14, 48, 934, DateTimeKind.Local).AddTicks(136),
                            Description = "ATM withdrawal",
                            Type = "Withdrawal"
                        },
                        new
                        {
                            TransactionId = 4,
                            AccountId = 4,
                            Amount = 500.00m,
                            CreatedAt = new DateTime(2025, 10, 8, 19, 14, 48, 934, DateTimeKind.Local).AddTicks(139),
                            Description = "Bonus",
                            Type = "Deposit"
                        },
                        new
                        {
                            TransactionId = 5,
                            AccountId = 5,
                            Amount = -25.00m,
                            CreatedAt = new DateTime(2025, 10, 8, 19, 14, 48, 934, DateTimeKind.Local).AddTicks(141),
                            Description = "Grocery",
                            Type = "Withdrawal"
                        });
                });

            modelBuilder.Entity("MyWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Password = "password1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Password = "password2"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "carol@example.com",
                            FirstName = "Carol",
                            LastName = "Williams",
                            Password = "password3"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            Password = "password4"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "eve@example.com",
                            FirstName = "Eve",
                            LastName = "Davis",
                            Password = "password5"
                        });
                });

            modelBuilder.Entity("MyWebApi.Models.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 10, 8),
                            Summary = "Mild",
                            TemperatureC = 20
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 10, 9),
                            Summary = "Warm",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2025, 10, 10),
                            Summary = "Cool",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2025, 10, 11),
                            Summary = "Hot",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2025, 10, 12),
                            Summary = "Chilly",
                            TemperatureC = 15
                        });
                });

            modelBuilder.Entity("MyWebApi.Models.Account", b =>
                {
                    b.HasOne("MyWebApi.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyWebApi.Models.Transaction", b =>
                {
                    b.HasOne("MyWebApi.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyWebApi.Models.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MyWebApi.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
